import './globals.css';

import { Inter } from 'next/font/google';

import { ClerkProvider } from '@clerk/nextjs';

import { ReactQueryProvider } from "./ReactQueryProvider";

import type { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark custom-bg`}>
        <ClerkProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
